version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: smsa-image:latest
    container_name: smsa-container
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
